/*******************************************************************************************
 * @Name         OfficePlayUtility
 * @Author       Damien Fleminks
 * @Description  Utility class to execute logic related to the Office_Play_config__c object
 *******************************************************************************************/

public with sharing class OfficePlayUtility {
  public OfficePlayUtility() {
  }
}
