/*******************************************************************************************
 * @Name         PlayerUtility
 * @Author       Damien Fleminks
 * @Description  Utility class to execute logic relaated to the Player__c object
 *******************************************************************************************/

public with sharing class PlayerUtility {
  public PlayerUtility() {
  }
}
